apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-monitor
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
    - istio-system
  selector:
    matchLabels:
      istio: ingressgateway
  endpoints:
  - port: http-envoy-prom
    path: /stats/prometheus
    interval: 15s 